SF #1930 Mail to Ticket: improved parsing of from: address
Combodo/combodo-email-synchro pull request #5
Opened 2020-12-13 13:57 UTC by jbostoen

Not sure whether this will be accepted, as I assume it's misconfiguration on the sender's part.

Anyhow, it's based on a real life case from about a week ago.

In a rare circumstance, an email From: header looked like this:  
`From: "Firstname Lastname" <firstname.lastname@domain.com >`

The client was Windows Live Mail, but it seems the email address was somehow misconfigured while still able to send emails.
This fix still processes invalid From: headers where there are spaces before or after the email address.
This regex is quite strict to prevent other issues from occurring because of this fix.

2020-12-13 17:49 UTC, Hipska requested changes
I think it would be better to update the original RegEx instead of adding an additional search.

2020-12-13 18:35 UTC, jbostoen commented
> 
> 
> I think it would be better to update the original RegEx instead of adding an additional search.

You might be right. The original thinking was to keep the traditional way of handling this; then use a fall back. But it could be simplified into one regex.

2020-12-14 09:45 UTC, Hipska commented
What if we use `^(.*)<([^>]+)>$` as RegEx and then also trim the `$sEmail`?

2020-12-14 09:51 UTC, jbostoen commented
> 
> 
> What if we use `^(.*)<([^>]+)>$` as RegEx and then also trim the `$sEmail`?

I actually deliberately tried to make it more strict to search for something which looks like an email between "<" and ">"

2020-12-14 09:59 UTC, Hipska commented
Yes I see that, but its not needed and also not RFC compliant.

Extra trimming can also be avoided with the following RegEx `^(.*)<\s*(.+?)\s*>$` If that is your concern.

2020-12-23 08:53 UTC, piRGoif commented
I agree with Thomas, changing the existing regexp should do the trick ? 
Can you change your code to match this strategy ? Beware to exclude invalid addresses like what is done below (setting $sEmail to an empty string)

2020-12-23 13:19 UTC, Hipska requested changes
Regex is still not RFC compliant, and why use actual spaces and white space mixed?

2021-01-22 16:45 UTC, piRGoif commented
Can you add a unit test, with for example :

```
name@domain.com
"Firstname Lastname" <name@domain.com>
"Firstname Lastname" <name@domain.com >
name @domain.com
Firstname Lastname name@domain.com
...
```

2021-01-22 17:05 UTC, jbostoen commented
How do I do so? Create a fake .EML message in the tests folder, and then what?

2021-01-22 17:12 UTC, piRGoif commented
I would say create a simple PHPUnit test with a dataprovider. The existing tests in `/test` are using eml files indeed, but I would say for this method we should test atomically.

I could try to code one myself... But seems I don't have rights to push to your fork's branch. Can you check if this is enabled ? (see [Allowing changes to a pull request branch created from a fork - GitHub Docs](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork))

2021-01-22 17:20 UTC, jbostoen commented
![image](https://user-images.githubusercontent.com/6421683/105523312-880d4c00-5cde-11eb-90fa-65cb166d06ab.png)

Seems to be enabled?

2021-01-25 08:15 UTC, Hipska approved these changes

2021-02-02 11:10 UTC, piRGoif commented
I've just add the test in \RawEmailMessageTest::testExtractAddressPieces
Can you check the dataProvider to see if there are any use cases to add ?

We will review the PR with the team.

2021-02-02 11:10 UTC, piRGoif approved these changes

2021-02-02 11:26 UTC, piRGoif commented
Wooops sorry, I've just ran the test on the master branch : it runs perfectly 🤔
That means that for the example you gave (`"Firstname Lastname" <name@domain.com >`), \RawEmailMessage::ExtractAddressPieces will return `['name'=>'Firstname Lastname', 'email'=>'name@domain.com']`

What change in behavior does your modification should bring ?

2021-02-02 12:39 UTC, Hipska commented
The original method on master branch would return `['name'=>'', 'email'=>'"Firstname Lastname" <firstname.lastname@domain.com >']`. Strange that you say the test runs OK.

2021-02-02 13:57 UTC, piRGoif commented
Oh sorry, I've just understand : I was running without symlinks in env-produciton, so I did change branch but didn't change the file content in `env-production/combodo-email-synchro/classes/rawemailmessage.class.inc.php`

Testing the correct file on the master branch, here is what I get : 
![image](https://user-images.githubusercontent.com/8947448/106610237-cddfd500-6566-11eb-9bee-dc05b3c7af2c.png)

All my apologies for my mistake ! 😕

I'm changing this PR labels, and this will be discussed with the team :) Stay tune !

2021-02-02 13:58 UTC, piRGoif approved these changes
Approving once again, now that I did test the right thing :o)

2021-02-02 14:03 UTC, Hipska commented
It seems the test does not cover the following case: https://github.com/Combodo/combodo-email-synchro/blob/11334586209b53cb1b35e44170d1c3084cf78f50/classes/rawemailmessage.class.inc.php#L917-L921

And also not this case: https://github.com/Combodo/combodo-email-synchro/blob/11334586209b53cb1b35e44170d1c3084cf78f50/classes/rawemailmessage.class.inc.php#L924-L929

2021-02-08 09:54 UTC, piRGoif commented
I've just pushed new commits : rename the existing test, and use a new method (was pushed in iTop repo to support/2.7 branch, which has just been merged to develop)

We reviewed this with the dev team on friday, they are ok to merge if the existing test pass : and I've just checked, it does !

@Hipska maybe the test I added isn't complete enough, but I prefer to merge like this as it is better than nothing. Don't hesitate to create a new PR afterwards to add more coverage !

2021-02-08 09:56 UTC, merged

2021-02-08 09:59 UTC, piRGoif commented
Wooops I almost forgot : Jeffrey could you provide an EML file to emulate the problem, so we can add it to the existing ones in `/test/emailsSample` ?

2021-02-08 10:16 UTC, piRGoif commented
Combodo internal ref : N°3708