SF #1925 Mail to Ticket: malformed headers
Combodo/combodo-email-synchro pull request #6
Opened 2020-12-13 14:06 UTC by jbostoen

Another issue I recently saw, while testing with old emails (2010/2011) sent to me, was that the "to:" field could actually contain things like "undisclosed recipient" instead of a proper email address. This results in PHP notices, also on the AJAX page.

Would a pull request be accepted for this rare issue where these warnings are simply suppressed?

2020-12-14 10:00 UTC, Hipska commented
Where do these PHP notices come from? Could you share?

2020-12-14 10:26 UTC, Hipska commented
Why always these force-pushes? It makes tracking changes in between much harder.

2020-12-14 10:27 UTC, jbostoen commented
The notice was something like `Unexpected characters at end of address: <> (errflg=3)` and appeared on the AJAX page where you can check the mailbox's content.

2020-12-14 10:28 UTC, Hipska commented
But on which php command / file / line is it triggered?

2020-12-14 11:40 UTC, Hipska requested changes

2020-12-14 11:40 UTC, Hipska commented on classes/imapemailsource.class.inc.php
> +		$sRawHeaders = imap_fetchheader($this->rImapConn, 1+$index);
Please remove the extra whitespace at the end.
```suggestion
		$sRawHeaders = imap_fetchheader($this->rImapConn, 1+$index);
```

2020-12-14 13:14 UTC, Hipska approved these changes

2021-03-26 08:38 UTC, piRGoif commented
As of #7, this is planned to be done in the next extension release that will be included in iTop 2.7.5 professional and essential.
Combodo internal ref : N°3859

2021-05-17 13:47 UTC, Molkobain commented
Hello Jeffrey,

Could you send me the email that was causing the issue ? We have a "happy christmas from oxford.eml" but there is no `To: <Undisclosed-Recipient:;>` in it. We can't merge the PR without reproducing the issue first.

Also, it seems that the PR only fixes it for the IMAP protocol, did you checked if it's already working with POP3?

Thanks!
Guillaume

2021-05-17 13:52 UTC, jbostoen commented
Hm, weird, this seems to be different (or perhaps it's interpreted differently by IMAP or the implementation).

Indeed, if I check now, the header is
`To: ";" <;>`

2021-05-19 13:09 UTC, Molkobain commented
Hello Jeffrey,

I'm sorry but we aren't gonna accept this PR. Despite the fact that intercepting IMAP errors (not only for the use case you have, but globally) would be a good idea, we don't want to include fixes that we cannot reproduce, especially in a module as complex and sensitive as this one.

Also, we would prefer the cause to be fix in both IMAP and POP3 protocols to avoid too many differences between them.

Take care,
Guillaume

2021-05-19 13:10 UTC, closed without merging