SF #1793 Mail to Ticket Automation: set IMAP undelete
Combodo/combodo-email-synchro pull request #8
Opened 2020-12-13 18:29 UTC by jbostoen

While debugging my own version of Mail to Ticket Automation; I stumbled upon something that may happen in obscure cases. Let's say for some reason emails were recovered from deleted folders in an IMAP source (for example: email got accidentally deleted because of an IMAP process).

Couldn't figure out why the email kept disappearing, despite commenting out all DeleteMessage() references. Turns out the deletion happened on disconnecting of the IMAP source. There, it closes the source with CL_EXPUNGE. However, when emails are restored from the recycle bin, apparently they keep the "marked for deletion" flag.

2020-12-14 11:35 UTC, Hipska commented
Reference: https://sourceforge.net/p/itop/tickets/1793/

I would have added a generic `$oSource->InitMessage($iMessage);` so there is no specific code in there, and then only in the IMAP class this would invoke `$this->UndeleteMessage($iMessage);`

And even maybe I would place it on these lines, so it only gets done when the message needs to be processed? 
https://github.com/Combodo/combodo-email-synchro/blob/0bbc4590009081cb5eb1af69b6ae9ffa66a1302d/classes/emailbackgroundprocess.class.inc.php#L328-L338

2020-12-14 11:39 UTC, Hipska requested changes

2020-12-14 11:39 UTC, Hipska commented on classes/imapemailsource.class.inc.php
> -	 }
Note that you broke this method.

2020-12-14 11:39 UTC, Hipska commented on classes/imapemailsource.class.inc.php
> +		return $ret;
```suggestion
		return imap_undelete($this->rImapConn, (1+$index).':'.(1+$index));
```

2020-12-14 12:01 UTC, jbostoen commented on classes/imapemailsource.class.inc.php
> +		return $ret;
I know it can be shorter. I did it to be consistent with the Delete function in this class.

2020-12-14 12:01 UTC, jbostoen commented on classes/imapemailsource.class.inc.php
> -	 }
Oops, nice catch!

2020-12-23 09:16 UTC, piRGoif commented
Thanks for the proposition !
Seems like a bug to restore a mail but still keeping its delete flag ?!?? Have you got any way to reproduce this ?
As this module also marks email for deletion, can there be a problem in case of a timeout of some kind, where the mail gest marked but the expunge command isn't sent ?

2020-12-23 12:02 UTC, jbostoen commented
I actually encountered it with Exchange online and the outlook client. I restored deleted items (not from the on between Trash folder). The flag was still set, causing it to be deleted again by iTop with the IMAP expunge command .

I have implemented this fix in my fork a year ago. Haven't seen side effects yet.

Kind regards
Jeffrey Bostoen

On Dec 23, 2020 10:17, Pierre Goiffon <notifications@github.com> wrote:

Thanks for the proposition !
Seems like a bug to restore a mail but still keeping its delete flag ?!?? Have you got any way to reproduce this ?
As this module also marks email for deletion, can there be a problem in case of a timeout of some kind, where the mail gest marked but the expunge command isn't sent ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/Combodo/combodo-email-synchro/pull/8#issuecomment-750029725>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ABQ7ZM43BKNJXVHFBWJVSJTSWGYQZANCNFSM4UZWGI6Q>.

2021-01-25 11:29 UTC, piRGoif commented
We need to have a chat on this with the rest of the dev team. I will let you know of the conclusions !

2021-01-25 11:34 UTC, Hipska approved these changes

2021-01-25 11:37 UTC, Hipska commented
@jbostoen What do you think of my suggestions? They would be more clean OOP.
> I would have added a generic `$oSource->InitMessage($iMessage);` so there is no specific code in there, and then only in the IMAP class this would invoke `$this->UndeleteMessage($iMessage);`
> 
> And even maybe I would place it on these lines, so it only gets done when the message needs to be processed?
> 
> https://github.com/Combodo/combodo-email-synchro/blob/0bbc4590009081cb5eb1af69b6ae9ffa66a1302d/classes/emailbackgroundprocess.class.inc.php#L328-L338

2021-01-25 14:38 UTC, jbostoen commented
It's also a possibility; not sure if there are more use cases or (short term) advantages though.

2021-01-25 14:44 UTC, Hipska commented
All I want is to get rid of `if($oSource instanceof IMAPEmailSource)`, it smells too much like a hack. Feel free to implement it another way.

2021-01-25 17:53 UTC, jbostoen commented
@piRGoif what's the preference on the trace message? Other tracing seems to happen mostly in the email background process?

2021-01-26 11:42 UTC, jbostoen commented
For the record: I used $index in the classes, to be consistent with existing code.

2021-01-29 15:59 UTC, piRGoif commented
Hello,

PR reviewed by the dev team. We are not really in favor as this could cause problems : 

* when a timeout occurs during the extension execution (problem I mentioned in a previous comment), if messages were already processed and flagged to be deleted
* on systems that are throttling mail clients (we had such issues with Office 365) : so changing flags for lots of tickets would cause additional operations that could be massive, and could cause the server to decide not disallow following operations

In consequence we are more in favor of adding details in the documentation... 
But we'll check with the products team, they may have a different opinion !

Stay tune !

2021-01-29 16:26 UTC, jbostoen commented
Just to be clear: it would only change something for the messages which are manually recovered after being accidentally deleted. That's the only impact.

Met vriendelijke groeten
Jeffrey Bostoen

On Jan 29, 2021 16:59, Pierre Goiffon <notifications@github.com> wrote:

Hello,

PR reviewed by the dev team. We are not really in favor as this could cause problems :

  *   when a timeout occurs during the extension execution (problem I mentioned in a previous comment), if messages were already processed and flagged to be deleted
  *   on systems that are throttling mail clients (we had such issues with Office 365) : so changing flags for lots of tickets would cause additional operations that could be massive, and could cause the server to decide not disallow following operations

In consequence we are more in favor of adding details in the documentation...
But we'll check with the products team, they may have a different opinion !

Stay tune !

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/Combodo/combodo-email-synchro/pull/8#issuecomment-769890722>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ABQ7ZM3EWAVOGW5VJ3YE7LLS4LLOZANCNFSM4UZWGI6Q>.

2021-01-29 17:20 UTC, Hipska commented
I understand the concerns of @piRGoif and they are indeed relevant because of the way you implemented it:

For every message in the mailbox, you will send the undelete command to IMAP before you even start processing it. That will cause a lot of commands if the system is configured to not remove the mails after processing, as all messages will stay in inbox then. This might indeed have impact, as he said in his second point, on O365 connections.

Then his first point is also valid. If the system is set to delete messages after processing, and it stops between processing of 2 messages (because of php or connection is killed), then the already processed messages will have this "deletion" flag, but are not actually deleted (expunge didn't happen). So in that case, the next run will undelete those messages again, which could be problematic and is not wanted.

[My suggestion](https://github.com/Combodo/combodo-email-synchro/pull/8#issuecomment-744381442) was to only do this 'undelete' for messages that are actually needed to be processed. I think that then both of these point are addressed. What do you think of that @piRGoif?

2021-01-29 17:31 UTC, piRGoif commented
Thanks for this rephrase Thomas :)

About the proposition to limit the scope of affected messages, this would mitigate the risk indeed, but still could cause issues not worst the benefits to my opinion (which might not be shared in the team).

So Jeffrey indeed I would recommend : 

* adopt Thomas' proposition
* optionally, add a feature flag, maybe disabled by default

I'm adding the question label waiting for Jeffrey's answer

2021-01-29 17:34 UTC, jbostoen commented
So what is the better solution? imap_headerinfo to check for delete flag? (only for messages which iTop thinks are **new** and for which no email replica exists)

2021-02-02 11:35 UTC, piRGoif commented
Hello,

> So what is the better solution?

Before writing any code, let me check first with the product team if they agree with this modification :) If they do, I'll ask the R&D team again.

2021-02-11 15:57 UTC, piRGoif commented
Hello,
We've just discussed this with the product team, and for the reasons explained (risk/gain ratio) we prefer to reject this PR.
Note that just after the iTop 3.0.0 release, we will spend some time on the Mail 2 Ticket extension, especially on the robustness part but also by adding functionalities (new Office 365 protocol, move processed mail to another folder, ...). We're not very sure yet of what will be done, and the products team will certainly contact you as you've done an amazing work on your fork !

2021-02-11 15:57 UTC, closed without merging

2021-02-25 19:34 UTC, jbostoen commented
@piRGoif  out of curiosity: which O365 protocol do you actually mean?

The moving to another folder also seems like a nice option. 👍

2021-02-26 09:12 UTC, piRGoif commented
I'm not an expert in this area 8)
Seems to be OAuth for MS Graph ? 
Combodo internal ref is N°2504